on:
  push:
      branches: [ home_task_2 ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: git clone https://github.com/google/googletest.git -b release-1.11.0
      - run: mkdir build
        working-directory: googletest
      - run: cmake ..
        working-directory: googletest/build      
      - run: make
        working-directory: googletest/build
      - run: sudo make install
        working-directory: googletest/build
      - run: sudo apt-get install -y python3 clang-tidy lcov valgrind cppcheck
      - run: linters/bash.sh
        working-directory: home_task_2
      - name: build_with_sanitizers
        run: g++ -fsanitize=address,undefined -fno-sanitize-recover=all -fsanitize-undefined-trap-on-error ./home_task_2/main.cc -Ihome_task_2/matrix_calculator_lib --std=c++17
      - name: run_built
        run: ./a.out
      - run: rm -rf build
        working-directory: home_task_2
      - run: mkdir build
        working-directory: home_task_2
      - run: cmake ..
        working-directory: home_task_2/build
      - run: cmake --build .
        working-directory: home_task_2/build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: main.out
      - name: test_with_valgrind
        run: valgrind --tool=memcheck --leak-check=yes ./tests/test_matrix_calculator
        working-directory: home_task_2/build